version: '2.0'

networks:
  basic-setup:
    name: basic-setup_ldes-network

services:

  ldes-mongodb:
    container_name: basic-setup_ldes-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - basic-setup

  ldes-server:
    container_name: basic-setup_ldes-server
    image: ldes/ldes-server:2.4.1-SNAPSHOT # you can safely change this to the latest 2.x.y version
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - basic-setup
    depends_on:
      - ldes-mongodb

  ldio-workbench:
    container_name: basic-setup_ldio-workbench
    image: ldes/ldi-orchestrator:1.10.0-SNAPSHOT # you can safely change this to the latest 1.x.y version
    volumes:
      - ./workbench/context.jsonld:/ldio/context.jsonld:ro
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - basic-setup 
