networks:
  basic-setup:
    name: basic-setup_ldes-network

services:

  ldes-postgresdb:
    container_name: basic-setup_ldes-postgresdb
    image: postgres:latest
    environment:
      - POSTGRES_DB=basic-setup
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - basic-setup

  ldes-server:
    container_name: basic-setup_ldes-server
    image: ldes/ldes-server:3.1.0-SNAPSHOT
    environment:
      - SERVER_PORT=80
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - LDESSERVER_HOSTNAME=http://localhost:9003/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/basic-setup
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - basic-setup
    depends_on:
      - ldes-postgresdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server/ldes/actuator/health"]

  ldio-workbench:
    container_name: basic-setup_ldio-workbench
    image: ldes/ldi-orchestrator:2.5.1
    volumes:
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - basic-setup 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]
