@startmindmap
* by-time
** year=2023
*** month=12
**** day=31
***** hour=15
***** hour=20
***** hour=21
** year=2024
*** month=1
**** day=15
***** hour=1
***** hour=8
***** hour=12
***** hour=19
**** day=20
***** hour=11
***** hour=12
@endmindmap
