networks:
  advanced-conversion:
    name: advanced-conversion_ldes-network

services:

  ldes-mongodb:
    container_name: advanced-conversion_ldes-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - advanced-conversion

  ldes-server:
    container_name: advanced-conversion_ldes-server
    image: ldes/ldes-server:2.14.0-SNAPSHOT
    environment:
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - LDESSERVER_HOSTNAME=http://localhost:9003/ldes
      - SPRING_DATA_MONGODB_URI=mongodb://ldes-mongodb/advanced-conversion
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - advanced-conversion
    depends_on:
      - ldes-mongodb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server/ldes/actuator/health"]

  ldio-workbench:
    container_name: advanced-conversion_ldio-workbench
    image: ldes/ldi-orchestrator:2.5.1-SNAPSHOT
    volumes:
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - advanced-conversion 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]
