version: '2.0'

networks:
  advanced-conversion:
    name: advanced-conversion_ldes-network

services:

  ldes-mongodb:
    container_name: advanced-conversion_ldes-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - advanced-conversion

  ldes-server:
    container_name: advanced-conversion_ldes-server
    image: ldes/ldes-server:2.9.0-SNAPSHOT # you can safely change this to the latest 2.x.y version
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - advanced-conversion
    depends_on:
      - ldes-mongodb
    environment:
      - MANAGEMENT_TRACING_ENABLED=false # TODO: remove this when pull-based tracing implemented

  ldio-workbench:
    container_name: advanced-conversion_ldio-workbench
    image: ldes/ldi-orchestrator:2.0.0-SNAPSHOT # you can safely change this to the latest 1.x.y version
    volumes:
      - ./workbench/config:/ldio/config:ro
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - advanced-conversion 
    profiles:
      - delay-started
