networks:
  advanced-conversion:
    name: advanced-conversion_ldes-network

services:

  ldes-postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - advanced-conversion


  ldes-server:
    image: ldes/ldes-server:3.6.1
    environment:
      - SERVER_PORT=80
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - LDESSERVER_HOSTNAME=http://localhost:9003/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
      - MANAGEMENT_TRACING_ENABLED=false
      - SPRING_TASK_SCHEDULING_POOL_SIZE=5
      - LDESSERVER_FRAGMENTATIONCRON=*/1 * * * * *
      - LDESSERVER_MAINTENANCECRON=-  # no retention / compaction / deletion
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - advanced-conversion
    depends_on:
      - ldes-postgresdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server/ldes/actuator/health"]


  ldio-workbench:
    image: ldes/ldi-orchestrator:2.12.0
    environment:
      - SERVER_PORT=80
    volumes:
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - advanced-conversion 
    depends_on:
      ldes-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]
