server:
  port: 80

orchestrator:
  pipelines:

    - name: p+r-pipeline
      description: "Traffic message in using HTTP, OSLO transformation, version creation & HTTP sending."
      input:
        name: Ldio:HttpIn
        adapter:
          name: Ldio:JsonToLdAdapter
          config:
            core-context: file:///ldio/context.jsonld
      transformers:
        - name: Ldio:VersionObjectCreator
          config:
            member-type: https://example.org/ns/mobility#offStreetParkingGround
            delimiter: "/"
            date-observed-property: <http://www.w3.org/ns/prov#generatedAtTime>
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://ldes-server/ldes/occupancy
            rdf-writer:
              content-type: application/n-quads
