networks:
  protected-setup-server:
    name: protected-setup_server-network
  protected-setup-client:
    name: protected-setup_client-network

services:

  ldes-postgresdb:
    container_name: protected-setup-server_ldes-postgresdb
    image: postgres:latest
    environment:
      - POSTGRES_DB=protected-setup
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - protected-setup-server


  ldes-server:
    container_name: protected-setup-server_ldes-server
    image: ldes/ldes-server:3.1.0-SNAPSHOT
    volumes:
      - ./ldes-server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - protected-setup-server
    depends_on:
      - ldes-postgresdb
    environment:
      - LDESSERVER_HOSTNAME=http://host.docker.internal:9003
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/protected-setup
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server/actuator/health"]
      interval: 12s
      timeout: 3s
      retries: 20

  server-workbench:
    container_name: protected-setup-server_server-workbench
    image: ldes/ldi-orchestrator:2.5.1
    volumes:
      - ./server-workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - protected-setup-server 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://server-workbench/actuator/health"]
    depends_on:
      - ldes-server


  client-workbench:
    container_name: protected-setup-server_client-workbench
    image: ldes/ldi-orchestrator:2.5.1
    environment:
      - SERVER_PORT=80
    volumes:
      - ./client-workbench/application.yml:/ldio/application.yml:ro
    networks:
      - protected-setup-client
    ports:
      - 9006:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - sink-system
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://client-workbench/actuator/health"]


  sink-system:
    container_name: protected-setup-server_sink-system
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:80
    networks:
      - protected-setup-client
    environment:
      - MEMORY=true
      - MEMBER_TYPE=http://schema.mobivoc.org/#ParkingLot
