services:

  ldes-server:
    environment:
    - SPRINGDOC_SWAGGERUI_PATH=/admin/doc/v1/swagger
    - SPRINGDOC_SWAGGERUI_URLSPRIMARYNAME=base

  reverse-proxy:
    image: nginx:stable
    ports:
      - 9005:8080
    volumes:
      - ./reverse-proxy/protect-ldes-server.conf:/etc/nginx/conf.d/protect-ldes-server.conf:ro
    depends_on:
      - ldes-server
    networks:
      - protected-setup-server 
