networks:
  publisher-network:
    name: broker-setup_publisher-network
  broker-network:
    name: broker-setup_broker-network

services:

  adminer:
    image: adminer:${ADMINER_TAG:-latest}
    ports:
      - 8085:8080
    networks:
      - publisher-network
      - broker-network

  ### -- Publisher --

  publisher-database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PUBLISHER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PUBLISHER_POSTGRES_PWD}
      - POSTGRES_DB=${PUBLISHER_POSTGRES_DB}
    networks:
      - publisher-network
    healthcheck:
      test: pg_isready -U ${PUBLISHER_POSTGRES_USER} -d ${PUBLISHER_POSTGRES_DB}


  publisher-server:
    image: ldes/ldes-server:3.6.1
    volumes:
      - ./publisher-server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - publisher-network
      - broker-network
    depends_on:
      publisher-database:
        condition: service_healthy
    environment:
      - LDESSERVER_HOSTNAME=http://publisher-server/ldes
      - SIS_DATA=/tmp
      - SERVER_PORT=80
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://publisher-database:5432/${PUBLISHER_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${PUBLISHER_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${PUBLISHER_POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
      - MANAGEMENT_TRACING_ENABLED=false
      - SPRING_TASK_SCHEDULING_POOL_SIZE=5
      - LDESSERVER_FRAGMENTATIONCRON=*/1 * * * * *
      - LDESSERVER_MAINTENANCECRON=0 0 12 * * * # daily at noon (UTC time)
      - LDESSERVER_COMPACTIONDURATION=P14D
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://publisher-server/ldes/actuator/health"]
      start_period: 45s


  publisher-workbench:
    image: ldes/ldi-orchestrator:2.12.0
    environment:
      - SERVER_PORT=80
    volumes:
      - ./publisher-workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - publisher-network 
    depends_on:
      publisher-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://publisher-workbench/actuator/health"]
      start_period: 5s


  ### -- Broker --

  broker-database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${BROKER_POSTGRES_DB}
      - POSTGRES_USER=${BROKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BROKER_POSTGRES_PWD}
    networks:
      - broker-network
    healthcheck:
      test: pg_isready -U ${BROKER_POSTGRES_USER} -d ${BROKER_POSTGRES_DB}


  broker-server:
    image: ldes/ldes-server:3.6.1
    volumes:
      - ./broker-server/application.yml:/application.yml:ro
    ports:
      - 9001:80
    networks:
      - broker-network
    depends_on:
      broker-database:
        condition: service_healthy
    environment:
      - LDESSERVER_HOSTNAME=http://localhost:9001/ldes
      - SIS_DATA=/tmp
      - SERVER_PORT=80
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://broker-database:5432/${BROKER_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${BROKER_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${BROKER_POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
      - MANAGEMENT_TRACING_ENABLED=false
      - SPRING_TASK_SCHEDULING_POOL_SIZE=5
      - LDESSERVER_FRAGMENTATIONCRON=*/30 * * * * * # every 30 seconds
      - LDESSERVER_MAINTENANCECRON=0 */3 * * * * # every 3 minutes
      - LDESSERVER_COMPACTIONDURATION=PT5M # keep only 5 minutes
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://broker-server/ldes/actuator/health"]
      start_period: 45s


  broker-workbench:
    image: ldes/ldi-orchestrator:2.12.0
    environment:
      - SERVER_PORT=80
    volumes:
      - ./broker-workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9002:80
    networks:
      - publisher-network
      - broker-network
    depends_on:
      broker-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://broker-workbench/actuator/health"]
      start_period: 5s
