networks:
  common-network:
    name: broker-setup_common-network

services:

  ### -- Publisher --

  publisher-database:
    container_name: broker-setup_publisher-database
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - common-network

  publisher-workbench:
    container_name: broker-setup_publisher-workbench
    image: ldes/ldi-orchestrator:2.5.1-SNAPSHOT
    volumes:
      - ./publisher-workbench/config:/ldio/config:ro
      - ./publisher-workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:80
    networks:
      - common-network 
    profiles:
      - delay-started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://publisher-workbench/actuator/health"]

  publisher-server:
    container_name: broker-setup_publisher-server
    image: ldes/ldes-server:2.14.0-SNAPSHOT
    volumes:
      - ./publisher-server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - common-network
    depends_on:
      - publisher-database
    environment:
      - LDES_SERVER_HOST_NAME=http://publisher-server/ldes
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://publisher-server/ldes/actuator/health"]


  ### -- Broker --

  broker-database:
    container_name: broker-setup_broker-database
    image: mongo:latest
    ports:
      - 27018:27017
    networks:
      - common-network

  broker-workbench:
    container_name: broker-setup_broker-workbench
    image: ldes/ldi-orchestrator:2.5.1-SNAPSHOT
    volumes:
      - ./broker-workbench/config:/ldio/config:ro
      - ./broker-workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9002:80
    networks:
      - common-network 
    profiles:
      - delay-started
    environment:
      - LDES_SERVER_URL=http://publisher-server/ldes/occupancy/by-page
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://broker-workbench/actuator/health"]

  broker-server:
    container_name: broker-setup_broker-server
    image: ldes/ldes-server:2.14.0-SNAPSHOT
    volumes:
      - ./broker-server/application.yml:/application.yml:ro
    ports:
      - 9001:80
    networks:
      - common-network
    depends_on:
      - broker-database
    environment:
      - LDES_SERVER_HOST_NAME=http://localhost:9001/ldes
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://broker-server/ldes/actuator/health"]
