server:
  port: 9006

orchestrator:
  pipelines:

    # This is a pipeline for demonstrating how to setup a pipeline to follow an existing LDES as a Data Client
    - name: client-pipeline
      description: "Replicates & synchronizes an existing LDES view and sends each member to a sink"
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: ${LDES_SERVER_URL}
          sourceFormat: application/n-triples
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://sink/member
