server:
  port: 9006

orchestrator:
  pipelines:

    # This is a pipeline for demonstrating how to setup a pipeline to follow an existing LDES as a Data Client
    - name: client-pipeline
      description: "Replicates & synchronizes an existing LDES view and sends each member to a sink"
      input:
        name: Ldio:LdesClient
        config:
          urls: 
            - ${LDES_SERVER_URL}
          sourceFormat: application/n-triples
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://sink/member
