logging:
  level:
    root: WARN
    be.vlaanderen.informatievlaanderen.ldes.server.Application: INFO

ldes-server:
  maintenance-cron: "-"  # no retention / compaction / deletion
  formatting:
    prefixes:
      mobility:           https://example.org/ns/mobility#
      occupancy:          http://localhost:9003/occupancy/
      mobivoc:            http://schema.mobivoc.org/#
      schema:             http://schema.org/
      wgs84_pos:          http://www.w3.org/2003/01/geo/wgs84_pos#
