server:
  port: 80

orchestrator:
  pipelines:

    # This is a pipeline for demonstrating CSV to linked data conversion using RML
    - name: park-n-ride-pipeline
      description: "Polls for CSV park-and-ride data, converts to linked data, creates versions & sends to LDES server."
      input:
        name: Ldio:HttpInPoller
        config:
          url: https://data.stad.gent/api/explore/v2.1/catalog/datasets/real-time-bezetting-pr-gent/exports/csv?lang=en&timezone=Europe%2FBrussels
          cron: 0 */2 * * * *
        adapter:
          name: Ldio:RmlAdapter
          config:
            mapping: ./config/csv-to-intermediate.ttl
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./config/intermediate-to-target.rq
        - name: Ldio:VersionObjectCreator
          config:
            member-type: http://schema.mobivoc.org/#ParkingLot
            delimiter: "#"
            date-observed-property: <http://purl.org/dc/terms/modified>
            generatedAt-property: http://purl.org/dc/terms/modified
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://ldes-server/ldes/occupancy
            rdf-writer:
              content-type: application/n-quads
