server:
  port: 80

orchestrator:
  pipelines:

    - name: p+r-pipeline
      description: "Traffic message in using HTTP, OSLO transformation, version creation & HTTP sending."
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpInPoller
        config:
          url: https://data.stad.gent/api/explore/v2.1/catalog/datasets/real-time-bezetting-pr-gent/exports/csv?lang=en&timezone=Europe%2FBrussels
          interval: PT1M
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RmlAdapter
          config:
            mapping: ./config/source-to-intermediate.ttl
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: ./config/intermediate-to-target.rq
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
          config:
            member-type: http://schema.mobivoc.org/#ParkingLot
            delimiter: "/"
            date-observed-property: <http://purl.org/dc/terms/modified>
            generatedAt-property: http://purl.org/dc/terms/modified
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://ldes-server/ldes/occupancy
            rdf-writer:
              content-type: application/n-quads
