server:
  port: 9006

orchestrator:
  pipelines:

    # This is a pipeline for demonstrating a basic LDES client which can replicate and synchronize an existing LDES
    - name: client-pipeline
      description: "Requests all existing members from a public LDES server and keeps following it for changes, sending each member as-is to a webhook"
      input:
        name: Ldio:LdesClient
        config:
          urls: 
            - ${LDES_SERVER_URL}
          sourceFormat: application/n-quads
          auth:
            type: API_KEY
            api-key-header: x-api-key
            api-key: client-two-secret
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: ${SINK_URL}
            rate-limit:
              enabled: true
              max-requests-per-minute: ${MAX_REQUESTS_PER_MINUTE}
