server:
  port: 9006

orchestrator:
  pipelines:

    # This is a pipeline for demonstrating how to setup a pipeline to follow an existing LDES as a Data Broker
    - name: client-pipeline
      description: "Replicates & synchronizes an existing LDES view, adds a location to each member and sends to the broker LDES Server"
      input:
        name: Ldio:LdesClient
        config:
          urls: 
            - ${LDES_SERVER_URL}
          sourceFormat: application/n-quads
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./config/occupancy-add-location.rq
            infer: true
      outputs:
        - name: Ldio:HttpOut
          config:
            endpoint: http://broker-server/ldes/occupancy
