networks:
  minimal-workbench:
    name: minimal-workbench_ldes-network

services:

  ldio-workbench:
    container_name: minimal-workbench_ldio-workbench
    image: ldes/ldi-orchestrator:2.5.1-SNAPSHOT
    volumes:
      - ./config/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:8080
    networks:
      - minimal-workbench 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench:8080/actuator/health"]
