networks:
  minimal-workbench:
    name: minimal-workbench_ldes-network

services:

  ldio-workbench:
    container_name: minimal-workbench_ldio-workbench
    image: ldes/ldi-orchestrator:2.3.0-SNAPSHOT # you can safely change this to the latest 2.x.y version
    volumes:
      - ./config/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:8080
    networks:
      - minimal-workbench 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server-workbench:8080/actuator/health"]
