networks:
  minimal-workbench:
    name: minimal-workbench_ldes-network

services:

  ldio-workbench:
    image: ldes/ldi-orchestrator:2.12.0
    environment:
      - SERVER_PORT=8080
    ports:
      - 9004:8080
    networks:
      - minimal-workbench 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench:8080/actuator/health"]
