networks:
  minimal-server:
    name: minimal-server_ldes-network

services:

  ldes-server:
    container_name: minimal-server_ldes-server
    image: ldes/ldes-server:3.1.0-SNAPSHOT
    environment:
      - SIS_DATA=/tmp
      - LDESSERVER_HOSTNAME=http://localhost:9003
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/minimal-server
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
    volumes:
      - ./config/application.yml:/application.yml:ro
    ports:
      - 9003:8080
    networks:
      - minimal-server
    depends_on:
      - ldes-postgresdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server:8080/actuator/health"]

  ldes-postgresdb:
    container_name: minimal-server_ldes-postgresdb
    image: postgres:latest
    environment:
      - POSTGRES_DB=minimal-server
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - minimal-server
