networks:
  minimal-server:
    name: minimal-server_ldes-network

services:

  ldes-server:
    container_name: minimal-server_ldes-server
    image: ldes/ldes-server:2.14.0
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://ldes-mongodb/minimal-server
      - LDESSERVER_HOSTNAME=http://localhost:9003
      - SIS_DATA=/tmp
    volumes:
      - ./config/application.yml:/application.yml:ro
    ports:
      - 9003:8080
    networks:
      - minimal-server
    depends_on:
      - ldes-mongodb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server:8080/actuator/health"]

  ldes-mongodb:
    container_name: minimal-server_ldes-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - minimal-server
