networks:
  minimal-server:
    name: minimal-server_ldes-network

services:

  ldes-server:
    image: ldes/ldes-server:3.6.0
    environment:
      - SIS_DATA=/tmp
      - LDESSERVER_HOSTNAME=http://localhost:9003
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
      - MANAGEMENT_TRACING_ENABLED=false
      - SPRING_TASK_SCHEDULING_POOL_SIZE=5
      - LDESSERVER_FRAGMENTATIONCRON=*/1 * * * * *
    volumes:
      - ./config/application.yml:/application.yml:ro
    ports:
      - 9003:8080
    networks:
      - minimal-server
    depends_on:
      - ldes-postgresdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server:8080/actuator/health"]

  ldes-postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - minimal-server
