server:
  port: 80

spring:
  data:
    mongodb:
      auto-index-creation: true

# springdoc:
#   swagger-ui:
#     path: /admin/doc/v1/swagger
#     urlsPrimaryName: base

management:
  tracing:
    enabled: false
