networks:
  public-ldes:
    name: public-ldes-network

services:

  ### -- Data Client --

  ldio-workbench:
    container_name: public-ldes_ldio-workbench
    image: ldes/ldi-orchestrator:2.5.1
    volumes:
      - ./application.yml:/ldio/application.yml:ro
    ports:
      - 9006:80
    networks:
      - public-ldes 
    depends_on:
      - sink-system
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]


  ### -- Backend System --

  sink-system:
    container_name: public-ldes_sink-system
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:80
    networks:
      - public-ldes
    depends_on:
      - sink-database
    environment:
      - MEMBER_TYPE=https://implementatie.data.vlaanderen.be/ns/vsds-verkeersmetingen#Verkeerstelling
      - CONNECTION_URI=mongodb://sink-database
      - DATABASE_NAME=public-ldes
      - COLLECTION_NAME=traffic-counts

  sink-database:
    container_name: public-ldes_sink-database
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - public-ldes
  