networks:
  public-ldes:
    name: public-ldes-network

services:

  ### -- Data Client --

  ldio-workbench:
    image: ldes/ldi-orchestrator:2.12.0
    environment:
      - SERVER_PORT=80
    ports:
      - 9006:80
    networks:
      - public-ldes 
    depends_on:
      - sink-system
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]


  ### -- Backend System --

  sink-system:
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:80
    networks:
      - public-ldes
    depends_on:
      - sink-database
    environment:
      - MEMBER_TYPE=https://implementatie.data.vlaanderen.be/ns/vsds-verkeersmetingen#Verkeerstelling
      - CONNECTION_URI=mongodb://sink-database
      - DATABASE_NAME=public-ldes
      - COLLECTION_NAME=traffic-counts

  sink-database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - public-ldes
  