server:
  port: 80

spring:
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    root: WARN
    be.vlaanderen.informatievlaanderen.ldes.server.Application: INFO

management:
  tracing:
    enabled: false
